import Layout from "globalComps/Layout";
import Head from 'next/head'
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import MakeReservationInputs from "./reservationPgComps/MakeReservationInputs";
import ReservationPgBtns from "./reservationPgComps/ReservationPgBtns";


function Reservations() {
    const { section } = useRouter().query
    const [rerenderComp, setRerenderComp] = useState(0)

    useEffect(() => {
        setRerenderComp(rerenderComp + 1)
    },[section])

    return (
        <Layout title="Camiguin Lazones Reservation Page" description="The reservations page of Camiguin Lazones Resort" keywords='reservations, Camiguin Lazones Resort, resort, stay'>
            <div className='reservationsPg'>
                <Head>
                    <title>Camiguin Lazones Resort Reservation Page</title>
                    <meta name="description" content="Generated by create next app" />
                </Head>
                <ReservationPgBtns/>
                <section className="h-100">
                    <section className="w-100 reservationInputFieldSec d-flex justify-content-center ps-5 pe-5">
                        <MakeReservationInputs/>
                    </section>
                </section>
            </div>
        </Layout>
    )
}


export default Reservations;