import NavBar from 'layout/navbar/NavBar'
import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import { FaAngleRight, FaAngleLeft, FaCircle, FaRegCircle } from 'react-icons/fa';
import Button from 'react-bootstrap/Button'
import { useState, MouseEvent } from 'react'
import styles from '../styles/Home.module.css'
import { introPic } from 'interfaces/interfaces';

const Home: NextPage = () => {
  const [pics, setPics] = useState<introPic[]>([{isOnUI: true, path: "interiorDinningRoom"} , {isOnUI: false, path: "interiorLivingRoom"}, {isOnUI: false, path: "interiorStairs"}, { isOnUI: false,  path: "introPic"}])
  const [indexPics, setIndexPics] = useState(0);


  const handleBtnClick = (event: MouseEvent<HTMLButtonElement>) => {
      // when the user clicks on this button, go to the next element in the pics state, and set isOn
  }

  return (
    <>
      <NavBar />
      <div className={`${styles.container} noPadding homePage`}>
        <Head>
          <title>Camiguin Lazones Resort Home Page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* ${styles.main} was using this below */}
        <main className={`noPadding noMargin d-flex flex-column justify-content-start border-bottom pb-2 min-vh-100`}>
          <section className="row noMargin">
            <div className='border-bottom pt-2 pb-2 col-12'>
              <h1 className={`${styles.title} mt-3 medFontWeight col-12`}>
                Welcome to Camguin Lazones Resort!
              </h1>
            </div>
          </section>
          <section className='row noMargin noPadding introPicsSec flex-nowrap'>
            <section className='border-bottom col-12 border noPadding noMargin'>
              <img src={`/imgs/${pics[indexPics].path}.jpeg`} alt="camiguin_lazones_resort_introPic" className='w-100 h-100' />
            </section>
          </section>
          <section className='row noMargin noPadding flex-nowrap'>
            <section className='d-flex justify-content-center align-items-center col-12'>
                {/* have an array of dots, if the user is on the specific picture then highlight that dot */}
                <section>
                {pics.map(({isOnUI}) => isOnUI ? <FaCircle className="me-1"/> : <FaRegCircle className="me-1"/>)}
                </section>
            </section>
          </section>
          <section className='row noMargin noPadding flex-nowrap'>
            <section className="d-flex justify-content-center align-items-center pt-2">
              <Button variant="secondary" className="me-1">
                <FaAngleLeft />
              </Button>
              <Button variant="secondary" className="m-1">
                <FaAngleRight />
              </Button>
            </section>
          </section>
          <section className={styles.grid}>

          </section>
        </main>

        {/* <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer> */}
      </div>
    </>
  )
}

export default Home
