import NavBar from 'layout/navbar/NavBar'
import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import { FaAngleRight, FaAngleLeft, FaCircle, FaRegCircle } from 'react-icons/fa';
import Button from 'react-bootstrap/Button'
import { useState, MouseEvent, useEffect } from 'react'
import styles from '../styles/Home.module.css'
import { introPic } from 'interfaces/interfaces';
import Image from "next/image"
import Logo from 'layout/Logo';
import IntroPicsSec from './HomePg/sections/IntroPicsSec';
import OurRoomsSec from './HomePg/sections/OurRooms/OurRoomsSec';
import { clientDomain } from '../data/appInfo';
import IntroToReviews from './HomePg/sections/Reviews/IntroToReviews';
import HospitalitySec from './HomePg/sections/HospitalitySec';
import ReviewsCarousel from './HomePg/sections/Reviews/ReviewsCarousel';
import Layout from 'globalComps/Layout';


const Home: NextPage = () => {
  return (
    <Layout title="Camiguin_Lazones_Resort_Home" description="The home page of Camiguin Lazones Resort" keywords='resort, Camiguin, hotel, stay' >
      <div className={`${styles.container} noPadding homePage min-vh-100`}>
        <Head>
          <title>Camiguin Lazones Resort Home Page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="noPadding noMargin d-flex flex-column justify-content-start pb-2 min-vh-100">
          <IntroPicsSec />
          <IntroToReviews/>
          <HospitalitySec/>

          
          {/* this section will contain all of the rooms that the user can choose from */}
          <section className='row ps-5 pe-5 mt-5'>
            <section className="col-12 homePgInfoSec ourRoomsSec shadow">
              <section className="w-100 d-flex justify-content-center align-items-center pt-3">
                <h3 className="display-3 d-flex">
                  <span className="fst-italic">
                    Enjoy Your Stay With Us
                  </span>
                  <span className='ms-2 d-block'>
                    🏠!
                  </span>
                </h3>
              </section>
              <section className="roomMainSec w-100 d-flex justify-content-center align-items-center pt-4 ">
                <OurRoomsSec/>
              </section>
            </section>
          </section>

          <section className='row ps-5 pe-5 mt-5 pb-5'>
            <section className="col-12 pitchSec shadow pb-5">
              <section className='pt-2'>
                <Logo width={100} height={100} />
              </section>
              <section className="titleSecPitchSec w-100 d-flex justify-content-center align-items-center pt-3">
                <h3 className="display-3 fst-italic">Why choose us?</h3>
              </section>
              <section className="pitchTxtSec w-100 d-flex justify-content-center align-items-center pt-4">
                <p className="display-6 text-center ps-4 pe-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia veniam unde quos natus culpa eligendi, ducimus, perferendis, tenetur qui quis dignissimos sapiente nulla aperiam sint similique vitae laudantium exercitationem. Sequi numquam quibusdam error voluptate reprehenderit magni impedit id adipisci ullam doloremque sit nisi deserunt necessitatibus veniam, quam incidunt placeat iste!</p>
              </section>
            </section>
          </section>
          <ReviewsCarousel/>

        </main>

        {/* <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer> */}
      </div>
      </Layout>
  )
}

export default Home
