import Layout from "globalComps/Layout";
import Head from 'next/head'
import ReservationPgBtns from "./reservationPg/ReservationPgBtns";


function reservations() {
    return (
        <Layout title="Camiguin Lazones Reservation Page" description="The reservations page of Camiguin Lazones Resort" keywords='reservations, Camiguin Lazones Resort, resort, stay'>
            <div className='reservationsPg'>
                <Head>
                    <title>Camiguin Lazones Resort Reservation Page</title>
                    <meta name="description" content="Generated by create next app" />
                </Head>
                <ReservationPgBtns/>
                {/* create the reservations page nav which will consist of the following: */}
                {/* reserve section: this will have the input */}
                {/* find reservations: this will have the a look up for past and current reservations */}
            </div>
        </Layout>
    )
}


export default reservations;