import NavBar from 'layout/navbar/NavBar'
import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import { FaAngleRight, FaAngleLeft, FaCircle, FaRegCircle } from 'react-icons/fa';
import Button from 'react-bootstrap/Button'
import { useState, MouseEvent, useEffect } from 'react'
import styles from '../styles/Home.module.css'
import { introPic } from 'globalInterfaces/interfaces';
import Image from "next/image"
import Logo from 'layout/Logo';
import IntroPicsSec from './HomePg/sections/IntroPicsSec';
import OurRoomsSec from './HomePg/sections/OurRooms/OurRoomsSec';
import { clientDomain } from '../data/appInfo';
import IntroToReviews from './HomePg/sections/Reviews/IntroToReviews';
import HospitalitySec from './HomePg/sections/HospitalitySec';
import ReviewsCarousel from './HomePg/sections/Reviews/ReviewsCarousel';
import Layout from 'globalComps/Layout';
import Reviews from '../data/reviews.json'
import MapSection from 'globalComps/Map';
import Map from 'globalComps/Map';


const Home: NextPage = () => {
  return (
    <Layout title="Camiguin_Lazones_Resort_Home" description="The home page of Camiguin Lazones Resort" keywords='resort, Camiguin, hotel, stay' >
      <div className={`${styles.container} noPadding homePage min-vh-100`}>
        <Head>
          <title>Camiguin Lazones Resort Home Page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="noPadding noMargin d-flex flex-column justify-content-start pb-2 min-vh-100">
          <IntroPicsSec />
          <IntroToReviews />
          <HospitalitySec />
          <section className='row d-flex justify-content-center align-items-center justify-content-sm-start align-items-sm-stretch d-sm-block ps-sm-5 pe-sm-5 mt-5'>
            <section className="col-12 homePgInfoSec ourRoomsSec shadow">
              <section className="w-100 d-flex justify-content-center align-items-center pt-3">
                <h3 className="display-3 d-flex">
                  <span className="fst-italic d-flex justify-content-center align-items-center smallerHeader text-center">
                    Enjoy Your Stay With Us 🏠!
                  </span>
                </h3>
              </section>
              <section className="roomMainSec w-100 d-flex justify-content-center align-items-center pt-4">
                <OurRoomsSec />
              </section>
            </section>
          </section>
          <section className="row ps-sm-5 pe-sm-5 mt-5 pb-5 d-flex justify-content-center align-items-center">
            <section className="col-12 pitchSec shadow pb-5">
              <section className='pt-2'>
                <Logo width={100} height={100} />
              </section>
              <section className="titleSecPitchSec w-100 d-flex justify-content-center align-items-center pt-3">
                <h3 className="display-3 fst-italic text-center">Why choose us?</h3>
              </section>
              <section className="pitchTxtSec w-100 d-flex justify-content-center align-items-center pt-4">
                <p className="display-6 text-center ps-4 pe-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia veniam unde quos natus culpa eligendi, ducimus, perferendis, tenetur qui quis dignissimos sapiente nulla aperiam sint similique vitae laudantium exercitationem. Sequi numquam quibusdam error voluptate reprehenderit magni impedit id adipisci ullam doloremque sit nisi deserunt necessitatibus veniam, quam incidunt placeat iste!</p>
              </section>
            </section>
          </section>
          <section className="row ps-sm-5 pe-sm-5 mt-5 pb-5 d-flex justify-content-center align-items-center">
            <section className="ourRoomsSec pt-4 reviewsMainSec justify-content-sm-start justify-content-center align-items-center align-items-sm-stretch w-100">
              <ReviewsCarousel reviews={Reviews} />
            </section>
          </section>
          <section>
            <section className="w-100 border-bottom">
              <h3 className="display-6 fst-italic w-100 text-center">Our address: </h3>
              <h6 className="display-6 fst-italic w-100 text-center">
                <a href="https://www.google.com/maps/place/Camiguin+Lanzones+Resort/@9.2403596,124.7325741,17z/data=!3m1!4b1!4m8!3m7!1s0x3300652515202d8d:0x7acb4a0181d6bd8a!5m2!4m1!1i2!8m2!3d9.2404019!4d124.7347173" rel="noreferrer" target="_blank" className="text-decoration-none text-dark underline-hover">
                  6PRM+4WR, Mambajao, Camiguin, Philippines
                </a>
              </h6>
              <h6 className="display-6 fst-italic w-100 text-center d-flex justify-content-center align-items-center">See you soon <span className='ms-2 shake'>👋</span> <span className="ms-2">!</span></h6>
            </section>
            <section className="d-flex justify-content-center align-items-center businessMapSec pt-4 pb-4">
              <Map />
            </section>
          </section>

        </main>
      </div>
    </Layout>
  )
}

export default Home
